#!/bin/bash
# Quick command reference for setting up your new Perimeter repository

echo "========================================"
echo "  Perimeter - New Repository Setup"
echo "========================================"
echo ""
echo "Your new repository is ready at: /tmp/perimeter-gateway"
echo ""
echo "🎯 STEP 1: Create GitHub Repository"
echo "   → Go to: https://github.com/new"
echo "   → Name: perimeter-gateway"
echo "   → Visibility: Public (or Private)"
echo "   → DO NOT initialize with README, .gitignore, or license"
echo ""
echo "🚀 STEP 2: Push to GitHub"
echo ""
echo "Run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "   cd /tmp/perimeter-gateway"
echo "   git remote add origin https://github.com/YOUR_USERNAME/perimeter-gateway.git"
echo "   git push -u origin main"
echo ""
echo "📊 Repository Stats:"
echo "   Files: $(find /tmp/perimeter-gateway -type f | wc -l)"
echo "   Commits: $(cd /tmp/perimeter-gateway && git rev-list --count HEAD)"
echo ""
echo "✅ Everything is ready to push!"
echo ""
