# AI Curation Engine - Render.com Blueprint Configuration
# Deploys all services for the complete demo application

services:
  # Main Demo Frontend (Web Service)
  - type: web
    name: ai-curation-demo
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard  # $7/month - required for persistent services
    region: oregon
    buildCommand: ""
    startCommand: "python demo/app.js"
    envVars:
      # Ollama connection (internal service reference)
      - key: OLLAMA_URL
        value: http://ollama-service:11434
      
      # Database connection
      - key: MONGODB_URI
        fromDatabase:
          name: curation-db
          type: pspg
          property: connectionString
      
      # Redis cache connection
      - key: REDIS_URL
        fromService:
          name: curation-cache
          type: redis
          property: connectionString
      
      # Python environment
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Application settings
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001
    
    healthCheckPath: /api/health

  # Ollama Background Worker (AI Processing Service)
  - type: worker
    name: ollama-service
    env: docker
    dockerfilePath: ./Dockerfile.ollama
    dockerContext: .
    plan: standard  # $7/month - for AI processing
    region: oregon
    dockerCommand: ""
    envVars:
      - key: OLLAMA_ORIGINS
        value: "*"
      - key: OLLAMA_HOST
        value: 0.0.0.0
    numInstances: 1

  # PostgreSQL Database (Free Starter Plan)
  - type: pspg
    name: curation-db
    plan: starter  # Free tier for development
    databaseName: curation_engine
    region: oregon

  # Redis Cache (Free Tier)
  - type: redis
    name: curation-cache
    plan: free  # Free tier
    region: oregon

