# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class ComprehensiveClassification(BaseModel):
    safety: typing.Optional["SafetyClassification"] = None
    educational: typing.Optional["EducationalValue"] = None
    viewpoint: typing.Optional["ViewpointAnalysis"] = None
    overall_confidence: typing.Optional[float] = None
    recommendation: typing.Optional[str] = None
    summary_reasoning: typing.Optional[str] = None

class EducationalValue(BaseModel):
    educational_score: typing.Optional[float] = None
    learning_objectives: typing.List[str]
    subject_areas: typing.List[str]
    cognitive_level: typing.Optional[str] = None
    reading_level: typing.Optional[int] = None
    factual_accuracy: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

class SafetyClassification(BaseModel):
    safety_score: typing.Optional[float] = None
    violence_level: typing.Optional[float] = None
    adult_content: typing.Optional[bool] = None
    hate_speech: typing.Optional[float] = None
    misinformation_risk: typing.Optional[float] = None
    age_appropriateness: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None
    content_warnings: typing.List[str]

class UserContext(BaseModel):
    age_category: typing.Optional[types.AgeCategory] = None
    jurisdiction: typing.Optional[types.Jurisdiction] = None
    parental_controls: typing.Optional[types.ParentalControls] = None
    sensitivity_level: typing.Optional[types.SensitivityLevel] = None

class ViewpointAnalysis(BaseModel):
    political_leaning: typing.Optional[str] = None
    bias_score: typing.Optional[float] = None
    perspective_diversity: typing.Optional[float] = None
    controversy_level: typing.Optional[float] = None
    source_credibility: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
