# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ComprehensiveClassification": types.ComprehensiveClassification,
    "stream_types.ComprehensiveClassification": stream_types.ComprehensiveClassification,

    "types.EducationalValue": types.EducationalValue,
    "stream_types.EducationalValue": stream_types.EducationalValue,

    "types.SafetyClassification": types.SafetyClassification,
    "stream_types.SafetyClassification": stream_types.SafetyClassification,

    "types.UserContext": types.UserContext,
    "stream_types.UserContext": stream_types.UserContext,

    "types.ViewpointAnalysis": types.ViewpointAnalysis,
    "stream_types.ViewpointAnalysis": stream_types.ViewpointAnalysis,


    "types.AgeCategory": types.AgeCategory,

    "types.Jurisdiction": types.Jurisdiction,

    "types.ParentalControls": types.ParentalControls,

    "types.SensitivityLevel": types.SensitivityLevel,

}