# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyEducational(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.EducationalValue:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyEducational", llm_response=llm_response, mode="request")
        return typing.cast(types.EducationalValue, result)

    def ClassifySafety(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SafetyClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySafety", llm_response=llm_response, mode="request")
        return typing.cast(types.SafetyClassification, result)

    def ClassifyViewpoint(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ViewpointAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyViewpoint", llm_response=llm_response, mode="request")
        return typing.cast(types.ViewpointAnalysis, result)

    def ComprehensiveContentAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ComprehensiveClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ComprehensiveContentAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.ComprehensiveClassification, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyEducational(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.EducationalValue:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyEducational", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.EducationalValue, result)

    def ClassifySafety(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SafetyClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySafety", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SafetyClassification, result)

    def ClassifyViewpoint(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ViewpointAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyViewpoint", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ViewpointAnalysis, result)

    def ComprehensiveContentAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ComprehensiveClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ComprehensiveContentAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ComprehensiveClassification, result)

    