# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ClassifyEducational(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EducationalValue:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ClassifyEducational(content=content,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyEducational", args={
                "content": content,
            })
            return typing.cast(types.EducationalValue, result.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifySafety(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> types.SafetyClassification:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ClassifySafety(content=content,user_context=user_context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifySafety", args={
                "content": content,"user_context": user_context,
            })
            return typing.cast(types.SafetyClassification, result.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyViewpoint(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ViewpointAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ClassifyViewpoint(content=content,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyViewpoint", args={
                "content": content,
            })
            return typing.cast(types.ViewpointAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def ComprehensiveContentAnalysis(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> types.ComprehensiveClassification:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ComprehensiveContentAnalysis(content=content,user_context=user_context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ComprehensiveContentAnalysis", args={
                "content": content,"user_context": user_context,
            })
            return typing.cast(types.ComprehensiveClassification, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyEducational(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EducationalValue, types.EducationalValue]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyEducational", args={
            "content": content,
        })
        return baml_py.BamlSyncStream[stream_types.EducationalValue, types.EducationalValue](
          result,
          lambda x: typing.cast(stream_types.EducationalValue, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EducationalValue, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ClassifySafety(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SafetyClassification, types.SafetyClassification]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifySafety", args={
            "content": content,"user_context": user_context,
        })
        return baml_py.BamlSyncStream[stream_types.SafetyClassification, types.SafetyClassification](
          result,
          lambda x: typing.cast(stream_types.SafetyClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SafetyClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ClassifyViewpoint(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ViewpointAnalysis, types.ViewpointAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyViewpoint", args={
            "content": content,
        })
        return baml_py.BamlSyncStream[stream_types.ViewpointAnalysis, types.ViewpointAnalysis](
          result,
          lambda x: typing.cast(stream_types.ViewpointAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ViewpointAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ComprehensiveContentAnalysis(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ComprehensiveClassification, types.ComprehensiveClassification]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ComprehensiveContentAnalysis", args={
            "content": content,"user_context": user_context,
        })
        return baml_py.BamlSyncStream[stream_types.ComprehensiveClassification, types.ComprehensiveClassification](
          result,
          lambda x: typing.cast(stream_types.ComprehensiveClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ComprehensiveClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyEducational(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyEducational", args={
            "content": content,
        }, mode="request")
        return result
    def ClassifySafety(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifySafety", args={
            "content": content,"user_context": user_context,
        }, mode="request")
        return result
    def ClassifyViewpoint(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyViewpoint", args={
            "content": content,
        }, mode="request")
        return result
    def ComprehensiveContentAnalysis(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ComprehensiveContentAnalysis", args={
            "content": content,"user_context": user_context,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyEducational(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyEducational", args={
            "content": content,
        }, mode="stream")
        return result
    def ClassifySafety(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifySafety", args={
            "content": content,"user_context": user_context,
        }, mode="stream")
        return result
    def ClassifyViewpoint(self, content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyViewpoint", args={
            "content": content,
        }, mode="stream")
        return result
    def ComprehensiveContentAnalysis(self, content: str,user_context: types.UserContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ComprehensiveContentAnalysis", args={
            "content": content,"user_context": user_context,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))