# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["ComprehensiveClassification","EducationalValue","SafetyClassification","ScamDetection","UserContext","ViewpointAnalysis",]
        ), enums=set(
          ["AgeCategory","Jurisdiction","ParentalControls","ScamType","SensitivityLevel","VulnerabilityType",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 6
    # #########################################################################

    @property
    def AgeCategory(self) -> "AgeCategoryViewer":
        return AgeCategoryViewer(self)

    @property
    def Jurisdiction(self) -> "JurisdictionViewer":
        return JurisdictionViewer(self)

    @property
    def ParentalControls(self) -> "ParentalControlsViewer":
        return ParentalControlsViewer(self)

    @property
    def ScamType(self) -> "ScamTypeViewer":
        return ScamTypeViewer(self)

    @property
    def SensitivityLevel(self) -> "SensitivityLevelViewer":
        return SensitivityLevelViewer(self)

    @property
    def VulnerabilityType(self) -> "VulnerabilityTypeViewer":
        return VulnerabilityTypeViewer(self)


    # #########################################################################
    # Generated classes 6
    # #########################################################################

    @property
    def ComprehensiveClassification(self) -> "ComprehensiveClassificationViewer":
        return ComprehensiveClassificationViewer(self)

    @property
    def EducationalValue(self) -> "EducationalValueViewer":
        return EducationalValueViewer(self)

    @property
    def SafetyClassification(self) -> "SafetyClassificationViewer":
        return SafetyClassificationViewer(self)

    @property
    def ScamDetection(self) -> "ScamDetectionViewer":
        return ScamDetectionViewer(self)

    @property
    def UserContext(self) -> "UserContextViewer":
        return UserContextViewer(self)

    @property
    def ViewpointAnalysis(self) -> "ViewpointAnalysisViewer":
        return ViewpointAnalysisViewer(self)



# #########################################################################
# Generated enums 6
# #########################################################################

class AgeCategoryAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("AgeCategory")
        self._values: typing.Set[str] = set([  "UNDER_13",  "UNDER_16",  "UNDER_18",  "ADULT",  ])
        self._vals = AgeCategoryValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "AgeCategoryValues":
        return self._vals


class AgeCategoryViewer(AgeCategoryAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class AgeCategoryValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def UNDER_13(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UNDER_13"))
    
    @property
    def UNDER_16(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UNDER_16"))
    
    @property
    def UNDER_18(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UNDER_18"))
    
    @property
    def ADULT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ADULT"))
    
    


class JurisdictionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Jurisdiction")
        self._values: typing.Set[str] = set([  "EU",  "US",  "INDIA",  "CHINA",  ])
        self._vals = JurisdictionValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "JurisdictionValues":
        return self._vals


class JurisdictionViewer(JurisdictionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class JurisdictionValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def EU(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("EU"))
    
    @property
    def US(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("US"))
    
    @property
    def INDIA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INDIA"))
    
    @property
    def CHINA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CHINA"))
    
    


class ParentalControlsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ParentalControls")
        self._values: typing.Set[str] = set([  "NONE",  "MILD",  "MODERATE",  "STRICT",  ])
        self._vals = ParentalControlsValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ParentalControlsValues":
        return self._vals


class ParentalControlsViewer(ParentalControlsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ParentalControlsValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def NONE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NONE"))
    
    @property
    def MILD(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MILD"))
    
    @property
    def MODERATE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MODERATE"))
    
    @property
    def STRICT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("STRICT"))
    
    


class ScamTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ScamType")
        self._values: typing.Set[str] = set([  "INVESTMENT_FRAUD",  "ROMANCE_SCAM",  "TECH_SUPPORT_SCAM",  "MEDICARE_SCAM",  "LOTTERY_SCAM",  "CHARITY_FRAUD",  "GRANDPARENT_SCAM",  "IDENTITY_THEFT",  "PHISHING",  "CRYPTOCURRENCY_SCAM",  ])
        self._vals = ScamTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ScamTypeValues":
        return self._vals


class ScamTypeViewer(ScamTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ScamTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def INVESTMENT_FRAUD(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INVESTMENT_FRAUD"))
    
    @property
    def ROMANCE_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ROMANCE_SCAM"))
    
    @property
    def TECH_SUPPORT_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TECH_SUPPORT_SCAM"))
    
    @property
    def MEDICARE_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDICARE_SCAM"))
    
    @property
    def LOTTERY_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOTTERY_SCAM"))
    
    @property
    def CHARITY_FRAUD(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CHARITY_FRAUD"))
    
    @property
    def GRANDPARENT_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("GRANDPARENT_SCAM"))
    
    @property
    def IDENTITY_THEFT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IDENTITY_THEFT"))
    
    @property
    def PHISHING(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PHISHING"))
    
    @property
    def CRYPTOCURRENCY_SCAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CRYPTOCURRENCY_SCAM"))
    
    


class SensitivityLevelAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("SensitivityLevel")
        self._values: typing.Set[str] = set([  "LOW",  "MEDIUM",  "HIGH",  ])
        self._vals = SensitivityLevelValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "SensitivityLevelValues":
        return self._vals


class SensitivityLevelViewer(SensitivityLevelAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class SensitivityLevelValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def LOW(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOW"))
    
    @property
    def MEDIUM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDIUM"))
    
    @property
    def HIGH(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("HIGH"))
    
    


class VulnerabilityTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("VulnerabilityType")
        self._values: typing.Set[str] = set([  "ELDERLY",  "INVESTMENT_SCAM_TARGET",  "FREQUENT_NEWS_CONSUMER",  "ISOLATION_RISK",  "COGNITIVE_IMPAIRMENT",  "RECENT_LOSS",  "FINANCIAL_STRESS",  ])
        self._vals = VulnerabilityTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "VulnerabilityTypeValues":
        return self._vals


class VulnerabilityTypeViewer(VulnerabilityTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class VulnerabilityTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def ELDERLY(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ELDERLY"))
    
    @property
    def INVESTMENT_SCAM_TARGET(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INVESTMENT_SCAM_TARGET"))
    
    @property
    def FREQUENT_NEWS_CONSUMER(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FREQUENT_NEWS_CONSUMER"))
    
    @property
    def ISOLATION_RISK(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ISOLATION_RISK"))
    
    @property
    def COGNITIVE_IMPAIRMENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("COGNITIVE_IMPAIRMENT"))
    
    @property
    def RECENT_LOSS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RECENT_LOSS"))
    
    @property
    def FINANCIAL_STRESS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FINANCIAL_STRESS"))
    
    



# #########################################################################
# Generated classes 6
# #########################################################################

class ComprehensiveClassificationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ComprehensiveClassification")
        self._properties: typing.Set[str] = set([  "safety",  "educational",  "viewpoint",  "scam_detection",  "overall_confidence",  "recommendation",  "summary_reasoning",  ])
        self._props = ComprehensiveClassificationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ComprehensiveClassificationProperties":
        return self._props


class ComprehensiveClassificationViewer(ComprehensiveClassificationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ComprehensiveClassificationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def safety(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("safety"))
    
    @property
    def educational(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("educational"))
    
    @property
    def viewpoint(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("viewpoint"))
    
    @property
    def scam_detection(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("scam_detection"))
    
    @property
    def overall_confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("overall_confidence"))
    
    @property
    def recommendation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("recommendation"))
    
    @property
    def summary_reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("summary_reasoning"))
    
    


class EducationalValueAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EducationalValue")
        self._properties: typing.Set[str] = set([  "educational_score",  "learning_objectives",  "subject_areas",  "cognitive_level",  "reading_level",  "factual_accuracy",  "reasoning",  ])
        self._props = EducationalValueProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EducationalValueProperties":
        return self._props


class EducationalValueViewer(EducationalValueAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class EducationalValueProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def educational_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("educational_score"))
    
    @property
    def learning_objectives(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("learning_objectives"))
    
    @property
    def subject_areas(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("subject_areas"))
    
    @property
    def cognitive_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("cognitive_level"))
    
    @property
    def reading_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reading_level"))
    
    @property
    def factual_accuracy(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("factual_accuracy"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    


class SafetyClassificationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SafetyClassification")
        self._properties: typing.Set[str] = set([  "safety_score",  "violence_level",  "adult_content",  "hate_speech",  "misinformation_risk",  "age_appropriateness",  "reasoning",  "content_warnings",  ])
        self._props = SafetyClassificationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SafetyClassificationProperties":
        return self._props


class SafetyClassificationViewer(SafetyClassificationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class SafetyClassificationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def safety_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("safety_score"))
    
    @property
    def violence_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("violence_level"))
    
    @property
    def adult_content(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("adult_content"))
    
    @property
    def hate_speech(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("hate_speech"))
    
    @property
    def misinformation_risk(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("misinformation_risk"))
    
    @property
    def age_appropriateness(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("age_appropriateness"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    @property
    def content_warnings(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("content_warnings"))
    
    


class ScamDetectionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ScamDetection")
        self._properties: typing.Set[str] = set([  "is_scam",  "scam_types",  "scam_confidence",  "urgency_tactics",  "too_good_to_be_true",  "requests_personal_info",  "unverified_claims",  "emotional_manipulation",  "warning_flags",  "protection_recommendation",  ])
        self._props = ScamDetectionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ScamDetectionProperties":
        return self._props


class ScamDetectionViewer(ScamDetectionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ScamDetectionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def is_scam(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("is_scam"))
    
    @property
    def scam_types(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("scam_types"))
    
    @property
    def scam_confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("scam_confidence"))
    
    @property
    def urgency_tactics(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("urgency_tactics"))
    
    @property
    def too_good_to_be_true(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("too_good_to_be_true"))
    
    @property
    def requests_personal_info(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("requests_personal_info"))
    
    @property
    def unverified_claims(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("unverified_claims"))
    
    @property
    def emotional_manipulation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("emotional_manipulation"))
    
    @property
    def warning_flags(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("warning_flags"))
    
    @property
    def protection_recommendation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("protection_recommendation"))
    
    


class UserContextAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("UserContext")
        self._properties: typing.Set[str] = set([  "age_category",  "jurisdiction",  "parental_controls",  "sensitivity_level",  "vulnerability_factors",  "protection_level",  ])
        self._props = UserContextProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "UserContextProperties":
        return self._props


class UserContextViewer(UserContextAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class UserContextProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def age_category(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("age_category"))
    
    @property
    def jurisdiction(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("jurisdiction"))
    
    @property
    def parental_controls(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parental_controls"))
    
    @property
    def sensitivity_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("sensitivity_level"))
    
    @property
    def vulnerability_factors(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("vulnerability_factors"))
    
    @property
    def protection_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("protection_level"))
    
    


class ViewpointAnalysisAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ViewpointAnalysis")
        self._properties: typing.Set[str] = set([  "political_leaning",  "bias_score",  "perspective_diversity",  "controversy_level",  "source_credibility",  "reasoning",  ])
        self._props = ViewpointAnalysisProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ViewpointAnalysisProperties":
        return self._props


class ViewpointAnalysisViewer(ViewpointAnalysisAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ViewpointAnalysisProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def political_leaning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("political_leaning"))
    
    @property
    def bias_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("bias_score"))
    
    @property
    def perspective_diversity(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("perspective_diversity"))
    
    @property
    def controversy_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("controversy_level"))
    
    @property
    def source_credibility(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("source_credibility"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    

